In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

/tmp/ipykernel_3608448/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

In [2]:
PLOTTING_BACKEND = "altair"

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 2
N_PRODUCERS = 2

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Resgo Blog Demo",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(risked=True, levered=True, chains=CHAINS, draws=DRAWS)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 11:04:07.967 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 11:04:07.971 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 11:04:07.974 | INFO     | resgo.engine.volumetric_simulator:simulate:72 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 11:04:07.974 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:77 - Resgo Blog Demo volumetric simulation complete!

2026-05-28 11:04:07.995 | INFO     | resgo.engine.production_simulator:prepare_simpack:142 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 11:04:07.995 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 1 start_idx = 8

2026-05-28 11:04:07.996 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 2 start_idx = 20

2026-05-28 11:04:07.998 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:232 - Flowing array initialized.

2026-05-28 11:04:08.001 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:419 - Recovery factors simulated.

2026-05-28 11:04:08.010 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:303 - Oil well rates initialized.

2026-05-28 11:04:08.010 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:319 - No gas producers, skipping gas rate initialization...

2026-05-28 11:04:08.010 | INFO     | resgo.engine.production_simulator:simulate:84 - Commencing field production simulation (2 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  37%|█████████████████████████████████████▏                                                              | 134/360 [00:00<00:00, 1336.04it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  36%|███████████████████████████████████▊                                                                | 129/360 [00:00<00:00, 1289.17it/s]

Chain 2:  38%|█████████████████████████████████████▌                                                              | 135/360 [00:00<00:00, 1347.59it/s]

Chain 3:  37%|████████████████████████████████████▉                                                               | 133/360 [00:00<00:00, 1324.43it/s]

2026-05-28 11:04:08.610 | SUCCESS  | resgo.engine.production_simulator:simulate:101 - Resgo Blog Demo Field production simulation complete!

2026-05-28 11:04:08.622 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:315 - Discount and inflation curves initialized

2026-05-28 11:04:08.830 | INFO     | resgo.engine.economic_simulator:simulate_capex:375 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 11:04:09.171 | INFO     | resgo.engine.economic_simulator:simulate_leverage:389 - Debt repayments simulated.

2026-05-28 11:04:09.172 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:402 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 11:04:09.176 | INFO     | resgo.engine.economic_simulator:simulate_prices:417 - Oil and Gas prices simulated using a flat price model.

2026-05-28 11:04:09.191 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:443 - Gross sales simulated.

2026-05-28 11:04:09.196 | INFO     | resgo.engine.economic_simulator:simulate_expenses:462 - OPEX and ABEX simulated.

2026-05-28 11:04:09.208 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:487 - Royalties simulated using a flat royalty model.

2026-05-28 11:04:09.216 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:513 - Infrastructure depreciation model simulated.

2026-05-28 11:04:09.226 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:527 - Producer depreciation model simulated.

2026-05-28 11:04:09.250 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:538 - Taxes simulated using a progressive tax model.

2026-05-28 11:04:09.250 | SUCCESS  | resgo.engine.economic_simulator:simulate:299 - Economic simulation of Resgo Blog Demo complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

          STOIIP (stb)                      GIIP (mscf)                       \
                    P1   P10  P50  P90  P99          P1   P10  P50  P90  P99
reservoir
Zone 1           102.6  47.4  9.3  0.0  0.0        49.7  21.6  3.2  0.0  0.0
Zone 2            56.8  31.6  0.0  0.0  0.0        30.0  14.0  0.0  0.0  0.0

          Condensate (stb)                     Solution Gas (mscf)        \
                        P1  P10  P50  P90  P99                  P1   P10
reservoir
Zone 1                 2.3  0.8  0.1  0.0  0.0               230.1  90.9
Zone 2                 1.5  0.5  0.0  0.0  0.0               125.2  62.7


            P50  P90  P99
reservoir
Zone 1     12.5  0.0  0.0
Zone 2      0.0  0.0  0.0

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

                 P1   P10  P50  P90  P99
Total Oil EUR  27.0  15.1  5.5  0.0  0.0

In [13]:
reporter.tabler.oil_eur_table()

            P1  P10  P50  P90  P99
producer
Oil 1     13.8  7.8  4.1  0.0  0.0
Oil 2     13.6  7.4  0.0  0.0  0.0

In [14]:
reporter.tabler.oil_eur_table()

            P1  P10  P50  P90  P99
producer
Oil 1     13.8  7.8  4.1  0.0  0.0
Oil 2     13.6  7.4  0.0  0.0  0.0

In [15]:
reporter.tabler.gas_eur_table(group_by=None)

                 P1   P10   P50  P90  P99
Total Gas EUR  87.6  44.3  13.4  0.0  0.0

In [16]:
reporter.tabler.gas_eur_table()

            P1   P10  P50  P90  P99
producer
Oil 1     45.9  23.9  9.3  0.0  0.0
Oil 2     43.9  21.9  0.0  0.0  0.0

In [17]:
reporter.tabler.gas_eur_table(group_by="reservoir")

             P1   P10  P50  P90  P99
reservoir
Zone 1     76.0  33.5  3.3  0.0  0.0
Zone 2     46.0  21.8  0.0  0.0  0.0

In [18]:
reporter.tabler.npv_table()

      P1  P10  P50  P90  P99
NPV  790  487  183  -16  -88